version: "3.7"
services:

  fac-base:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-base:${FAC_BASE_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.base"
      args:
        - BASE_IMAGE_TAG=${DEBIAN_TAG}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"

  fac-epics:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-epics:${FAC_EPICS_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.epics"
      args:
        - BASE_IMAGE_TAG=${FAC_BASE_TAG}
        - ANSIBLE_TAG=${FAC_ANSIBLE_TAG}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"

  fac-apps:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-apps:${FAC_APPS_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.apps"
      args:
        - BASE_IMAGE_TAG=${FAC_EPICS_TAG}
        - ANSIBLE_TAG=${FAC_ANSIBLE_TAG}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"

  fac-iocs:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:${FAC_IOCS_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.iocs"
      args:
        - BASE_IMAGE_TAG=${FAC_APPS_TAG}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"
