ARG BASE_IMAGE_TAG
ARG ANSIBLE_TAG
FROM dockerregistry.lnls-sirius.com.br/fac/fac-apps:${BASE_IMAGE_TAG}

SHELL ["bash", "-c"]

WORKDIR /opt

# copy all entry-points to image
COPY ./iocs-log /

RUN source /etc/profile

CMD ["/bin/bash"]
