version: "3.7"
services:
  bo-ps-fams:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:2020-02-19
    command: bash -c 'source /etc/profile && /iocs-service/bo-ps-fams.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == TA-TiRack-CO-FWSrv-1
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
