version: "3.7"

services:

  spect-quads-lens:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs-li-ps:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/li-ps-spect-quads-lens.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == samba
      resources:
        limits:
          cpus: "8"
          memory: 16G
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
    networks:
      - ioc-network

  corrs:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs-li-ps:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/li-ps-corrs.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == samba
      resources:
        limits:
          cpus: "8"
          memory: 16G
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
    networks:
      - ioc-network

  slnds:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs-li-ps:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/li-ps-slnds.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == bossanova
      resources:
        limits:
          cpus: "8"
          memory: 16G
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
    networks:
      - ioc-network

  conv:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "spect-quads-lens"
      - "corrs"
      - "slnds"
    command: bash -c '/ioc-apps/li-ps-conv.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == bossanova
      resources:
        limits:
          cpus: "8"
          memory: 16G
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
    networks:
      - ioc-network

  diag:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "spect-quads-lens"
      - "corrs"
      - "slnds"
    command: bash -c '/ioc-apps/li-ps-diag.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == samba
      resources:
        limits:
          cpus: "8"
          memory: 16G
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
