version: "3.7"

services:

  tbts-bodip:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-tbts-bodip.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-16RaBbB-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia01:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia01.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaTim-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia02:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia02.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaTim-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia03:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia03.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia04:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia04.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaTim-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia05:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia05.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia06:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia06.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaTim-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia07:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia07.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == lnlsfac-srv2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia08:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia08.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia09:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia09.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == lnlsfac-srv2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia10:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia10.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-16RaBbB-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia11:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia11.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-16RaBbB-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia12:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia12.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaTim-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia13:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia13.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia14:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia14.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia15:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia15.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia16:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia16.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia17:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia17.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia18:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia18.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaTim-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia19:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia19.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  ia20:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/as-ps-dclinks-ia20.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == lnlsfac-srv2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
