version: "3.7"

services:

  dips:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/bo-ps-dips.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  quads:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-quads.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ia-20radiag02-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  sexts:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-sexts.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia01:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia01.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia02:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia02.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia04:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia04.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-2
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia05:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia05.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-2
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia07:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia07.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia08:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia08.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ia-14radiag03-co-iocsrv
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia10:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia10.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ia-20radiag02-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia11:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia11.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia13:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia13.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia14:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia14.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia16:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia16.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ia-20radiag02-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia17:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia17.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ia-20radiag02-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs-ia20:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/bo-ps-corrs-ia20.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-2
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
