version: "3.7"

services:

  facs-csconsts:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-csconsts:__FAC_CSCONSTS_TAG_TEMPLATE__
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == elisa
      resources:
        limits:
          cpus: "8"
          memory: 16G
      replicas: 1
      restart_policy:
        condition: any
      labels:
        io.portainer.accesscontrol.public: ""
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50m"
    networks:
      - host_network

networks:
  host_network:
    external:
      name: "host"
