version: "3.7"

services:

  dips:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/ts-ps-dips.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  quads:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/ts-ps-quads.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c '/ioc-apps/ts-ps-corrs.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
