version: "3.7"

services:

  dips:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/tb-ps-dips.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  quads:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c 'source /etc/profile && /ioc-apps/tb-ps-quads.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  corrs:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    depends_on:
      - "dips"
    command: bash -c 'source /etc/profile && /ioc-apps/tb-ps-corrs.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-18RaDiag04-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
