version: "3.7"

services:

  facs-csconsts:
    image: ghcr.io/lnls-sirius/control-system-constants:__FAC_CSCONSTS_TAG_TEMPLATE__
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == CA-RaCtrl-CO-Srv-1
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - host_network

networks:
  host_network:
    external:
      name: "host"
