version: "3.7"

services:

  iocs:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c 'source /etc/profile && /ioc-apps/ts-ps-corrs.bash'
    deploy:
      placement:
        constraints:
          - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
