version: "3.7"

services:

  #as-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/as-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  #li-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/li-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  #tb-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/tb-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  #bo-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/bo-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  #ts-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/ts-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  #si-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/si-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  #ba-general:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/ba-ti-general.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  bo-bpms-corrs:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/bo-ti-bpms-corrs.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-2
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

  #si-bpms-corrs:
  #  image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
  #  command: bash -c '/ioc-apps/si-ti-bpms-corrs.bash'
  #  volumes:
  #    - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.hostname == IA-20RaDiag02-CO-IOCSrv-2
  #    replicas: 1
  #    restart_policy:
  #      condition: any
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-file: "10"
  #      max-size: "10m"
  #  networks:
  #    - ioc-network

  si-trims-skews:
    image: ghcr.io/lnls-sirius/docker-machine-applications/fac-iocs:__FAC_IOC_TAG_TEMPLATE__
    command: bash -c '/ioc-apps/si-ti-trims-skews.bash'
    volumes:
      - "/storage/common/fac/iocs-log:/home/sirius/iocs-log"
    deploy:
      placement:
        constraints:
          - node.hostname == ca-ratim-co-iocsrv-1
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
