version: "3.7"
services:
  ts-ps:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:2020-02-26
    command: bash -c 'source /etc/profile && /iocs-service/si-ps-corrs-c134.bash'
    deploy:
      placement:
        constraints:
          - node.hostname != CA-RaTim-CO-IOCSrv
          # - node.hostname != IA-14RaDiag03-CO-IOCSrv
          # - node.hostname != IA-16RaBbB-CO-IOCSrv
          # - node.hostname != IA-18RaDiag04-CO-IOCSrv
          # - node.hostname != IA-20RaDiag01-CO-IOCSrv-1
          # - node.hostname != IA-20RaDiag01-CO-IOCSrv-2
          # - node.hostname != IA-20RaDiag02-CO-IOCSrv-1
          # - node.hostname != IA-20RaDiag02-CO-IOCSrv-2
          - node.hostname != CA-RaCtrl-CO-Srv-1
          - node.hostname != LA-RaCtrl-CO-Srv-1
          - node.hostname != TA-TiRack-CO-FWSrv-1
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - ioc-network

networks:
  ioc-network:
    external: true
    name: "host"
