ARG BASE_IMAGE_TAG
FROM dockerregistry.lnls-sirius.com.br/debian:${BASE_IMAGE_TAG}

SHELL ["bash", "-c"]

WORKDIR /opt

ARG ANSIBLE_VERSION
RUN set -e; \
    set -x; \
    \
    apt update; \
    apt -y install git python python-pip sudo systemd wget nano cron; \
    pip install ansible==${ANSIBLE_VERSION}

CMD ["/bin/bash"]
