ARG BASE_IMAGE_TAG
FROM dockerregistry.lnls-sirius.com.br/fac/fac-epics:${BASE_IMAGE_TAG}

SHELL ["bash", "-c"]

WORKDIR /opt

ARG ANSIBLE_TAG
RUN set -e; \
    set -x; \
    ln -f -s /bin/true /bin/systemctl; \
    rm -rf lnls-ansible; \
    git clone https://github.com/lnls-sirius/lnls-ansible.git; \
    cd lnls-ansible; \
    git checkout ${ANSIBLE_TAG}; \
    \
    ansible-playbook --connection=local playbooks/playbook-fac-services-apps.yml

RUN source /etc/profile

CMD ["/bin/bash"]
