ARG BASE_IMAGE_TAG
FROM dockerregistry.lnls-sirius.com.br/fac/fac-apps:${BASE_IMAGE_TAG}

SHELL ["bash", "-c"]

WORKDIR /opt

RUN mkdir -p /ioc-apps
RUN mkdir -p /ioc-logs

COPY applications/*.bash /ioc-apps/

RUN source /etc/profile

CMD ["/bin/bash"]
