version: "3.7"
services:

  fac-base:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-base:${FAC_IMG_BASE_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.base"
      args:
        - BASE_IMAGE_TAG=${FAC_IMG_DEBIAN_TAG}
        - ANSIBLE_VERSION=${FAC_PKG_ANSIBLE_VERSION}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"

  fac-epics:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-epics:${FAC_IMG_EPICS_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.epics"
      args:
        - BASE_IMAGE_TAG=${FAC_IMG_BASE_TAG}
        - ANSIBLE_TAG=${FAC_REP_ANSIBLE_VERSION}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"

  fac-apps:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-apps:${FAC_IMG_APPS_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.apps"
      args:
        - BASE_IMAGE_TAG=${FAC_IMG_EPICS_TAG}
        - ANSIBLE_TAG=${FAC_REP_ANSIBLE_VERSION}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"

  fac-iocs:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-iocs:${FAC_IMG_IOCS_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.iocs"
      args:
        - BASE_IMAGE_TAG=${FAC_IMG_APPS_TAG}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    command: "sleep infinity"
