ARG IMG_DEPS_MODELS_TAG
FROM ghcr.io/lnls-sirius/docker-machine-applications/fac-models-deps:${IMG_DEPS_MODELS_TAG}
# --- size 2.43 GB

SHELL ["bash", "-c"]

WORKDIR /opt/repos

# -------------------------------------------------------------------
# 1) Clone trackcpp and install inside sirius env
# -------------------------------------------------------------------
RUN git clone https://github.com/lnls-fac/trackcpp.git && \
    cd trackcpp && make install && make clean
# --- size 2.44 GB

# -------------------------------------------------------------------
# 2) Clone repos (no build yet)
# -------------------------------------------------------------------
RUN git clone https://github.com/lnls-fac/mathphys.git && \
    git clone https://github.com/lnls-fac/pyaccel.git && \
    git clone https://github.com/lnls-fac/pymodels.git && \
    git clone https://github.com/lnls-sirius/dev-packages.git && \
    git clone https://github.com/lnls-sirius/machine-applications-models.git
# # --- size 2.48 GB

# # -------------------------------------------------------------------
# # 3) Build all packages inside micromamba environment
# # -------------------------------------------------------------------
RUN cd mathphys && make install && \
    cd .. && cd dev-packages/siriuspy && make install && cd .. && \
    cd .. && cd pyaccel && make install && \
    cd .. && cd pymodels && make install
# # --- size 2.49 GB

# # # ---------------------------
# # # 4) install model-based IOCs
# # # ---------------------------
RUN cd machine-applications-models && \
    git checkout add-si-ap-injbeamdiag && \make install
# # # --- size 3.17 GB

# # # ---------------------
# # # 5) epics address list
# # # ---------------------
ENV EPICS_CA_ADDR_LIST="10.128.1.12:5064 10.128.1.12:5070 10.128.1.54:5064 10.128.1.55:5064 10.128.1.13:5064 10.128.1.13:5068 10.128.1.13:5070 10.0.38.29:5064 10.0.38.37:5064 10.0.38.39:5064 10.0.38.52:5064 10.0.38.93:5064 10.30.14.19 10.10.10.139"
