ARG IMG_EPICS_TAG
FROM ghcr.io/lnls-sirius/docker-machine-applications/fac-epics:${IMG_EPICS_TAG}

SHELL ["bash", "-c"]

WORKDIR /opt

ENV DEBIAN_FRONTEND noninteractive

# Install pip-package dependencies

RUN pip-sirius install \
    aiohttp:pkg_version_aiohttp \
    bottleneck:pkg_version_bottleneck \
    python-dateutil \
    urllib3 \
    scipy:pkg_version_scipy \
    pydantic \
    pyyaml \
    serial \
    toml \
    GPy:pkg_version_gpy \
    h5py:pkg_version_h5py
