FROM fac-epics-python2

SHELL ["bash", "-c"]

WORKDIR /opt

ENV DEBIAN_FRONTEND noninteractive

# Create IOC-related directories

RUN mkdir -p /ioc-apps && \
    mkdir -p /ioc-logs

# Copy bash-file applications

COPY apps/li-ps-*.bash /ioc-apps/

# Install IOC-related lnls-sirius packages

RUN cd repos && \
    git -c http.sslVerify=false clone https://gitlab.cnpem.br/FACS/linac-ioc-ps && \
    cd linac-ioc-ps && \
    git checkout :pkg_version_linac_ioc_ps && \
    ./setup.py install --single-version-externally-managed --compile --force --record /dev/null
